name: Flutter Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  analyze:
    name: Analyze Flutter Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run tests (if available)
        run: flutter test || true

  build_android:
    name: Build Android APK and Bundle
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  build_ios:
    name: Build iOS IPA
    needs: analyze
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install fastlane
          gem install cocoapods

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS archive
        run: |
          flutter build ios --release --no-codesign

      - name: Package as IPA (without signing)
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r app-release-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned-ipa
          path: app-release-unsigned.ipa
