name: Create Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  build_ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install CocoaPods
        run: |
          gem install cocoapods

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS archive
        run: |
          flutter build ios --release --no-codesign

      - name: Package as IPA (without signing)
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r app-release-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned-ipa
          path: app-release-unsigned.ipa

  create_release:
    name: Create Release
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: app-release-apk

      - name: Download AAB
        uses: actions/download-artifact@v3
        with:
          name: app-release-bundle

      - name: Download IPA
        uses: actions/download-artifact@v3
        with:
          name: app-release-unsigned-ipa

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            app-release.apk
            app-release.aab
            app-release-unsigned.ipa
